backend:
  name: github
  repo: balt1ka0/news-for-tv-noauto
  branch: main
  # base_url: https://news-for-tv-noauto.kkkkk-kee-49f.workers.dev

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "news"
    label: "Новости"
    label_singular: "Новость"
    folder: "content"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Ссылка", name: "link", widget: "string", required: false }
      - { label: "Краткое описание", name: "summary", widget: "text" }
      - { label: "Категория", name: "category", widget: "select", options: ["Хайтек", "Наука", "Технологии", "Умное садоводство"] }
      - { label: "Дата публикации", name: "pub_date", widget: "datetime" }
